//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class buscon_kondisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buscon_kondisi()
        {
            this.buscon_kondisi_berkas = new HashSet<buscon_kondisi_berkas>();
            this.buscon_kriteria_berkas = new HashSet<buscon_kriteria_berkas>();
        }
    
        public int id_kondisi { get; set; }
        public string kondisi { get; set; }
        public string kriteria { get; set; }
        public Nullable<int> id_judul_buscon { get; set; }
    
        public virtual buscon_judul buscon_judul { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buscon_kondisi_berkas> buscon_kondisi_berkas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buscon_kriteria_berkas> buscon_kriteria_berkas { get; set; }
    }
}
