//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class buscon_anggota
    {
        public int id_anggota_buscon { get; set; }
        public Nullable<int> id_buscon { get; set; }
        public Nullable<int> user { get; set; }
    
        public virtual buscon buscon { get; set; }
        public virtual User User1 { get; set; }
    }
}
