//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class buscon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buscon()
        {
            this.buscon_anggota = new HashSet<buscon_anggota>();
            this.buscon_remind_once = new HashSet<buscon_remind_once>();
            this.buscon_remind_weekly = new HashSet<buscon_remind_weekly>();
        }
    
        public int id_buscon { get; set; }
        public Nullable<int> perusahaan { get; set; }
        public Nullable<int> review { get; set; }
        public string review_name { get; set; }
        public string no_report_fra { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<System.DateTime> penugasan_start { get; set; }
        public Nullable<System.DateTime> penugasan_end { get; set; }
        public Nullable<int> ketua_tim { get; set; }
        public string status_final { get; set; }
        public Nullable<int> created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buscon_anggota> buscon_anggota { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buscon_remind_once> buscon_remind_once { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buscon_remind_weekly> buscon_remind_weekly { get; set; }
        public virtual review review1 { get; set; }
        public virtual buscon_judul buscon_judul { get; set; }
        public virtual perusahaan perusahaan1 { get; set; }
    }
}
