//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class buscon_progress_berkas
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public Nullable<int> id_progress { get; set; }
    
        public virtual buscon_progress buscon_progress { get; set; }
    }
}
