//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class buscon_judul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buscon_judul()
        {
            this.buscon_kondisi = new HashSet<buscon_kondisi>();
        }
    
        public int id_judul_buscon { get; set; }
        public Nullable<int> id_buscon { get; set; }
        public string judul { get; set; }
    
        public virtual buscon buscon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buscon_kondisi> buscon_kondisi { get; set; }
    }
}
