//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mpmEntities : DbContext
    {
        public mpmEntities()
            : base("name=mpmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<buscon> buscons { get; set; }
        public virtual DbSet<buscon_anggota> buscon_anggota { get; set; }
        public virtual DbSet<buscon_judul> buscon_judul { get; set; }
        public virtual DbSet<buscon_kondisi> buscon_kondisi { get; set; }
        public virtual DbSet<buscon_kondisi_berkas> buscon_kondisi_berkas { get; set; }
        public virtual DbSet<buscon_kriteria_berkas> buscon_kriteria_berkas { get; set; }
        public virtual DbSet<buscon_progress> buscon_progress { get; set; }
        public virtual DbSet<buscon_progress_berkas> buscon_progress_berkas { get; set; }
        public virtual DbSet<buscon_remind_once> buscon_remind_once { get; set; }
        public virtual DbSet<buscon_remind_weekly> buscon_remind_weekly { get; set; }
        public virtual DbSet<buscon_sebab_akibat> buscon_sebab_akibat { get; set; }
        public virtual DbSet<divisi> divisis { get; set; }
        public virtual DbSet<hirarki> hirarkis { get; set; }
        public virtual DbSet<perusahaan> perusahaans { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<simo> simoes { get; set; }
        public virtual DbSet<simo_detail> simo_detail { get; set; }
        public virtual DbSet<simo_detail_berkas> simo_detail_berkas { get; set; }
        public virtual DbSet<simo_detail_berkas_deskripsi> simo_detail_berkas_deskripsi { get; set; }
        public virtual DbSet<simo_detail_pic> simo_detail_pic { get; set; }
        public virtual DbSet<simo_remind_date> simo_remind_date { get; set; }
        public virtual DbSet<simo_remind_weekly> simo_remind_weekly { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
