//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class simo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public simo()
        {
            this.simo_detail = new HashSet<simo_detail>();
            this.simo1 = new HashSet<simo>();
            this.simo11 = new HashSet<simo>();
            this.simo_remind_date = new HashSet<simo_remind_date>();
            this.simo_remind_weekly = new HashSet<simo_remind_weekly>();
        }
    
        public int id { get; set; }
        public string review_name { get; set; }
        public string no_review { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string tempat { get; set; }
        public string peserta { get; set; }
        public string jam { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> id_perusahaan { get; set; }
        public Nullable<bool> status_lanjut { get; set; }
        public Nullable<int> id_sebelum { get; set; }
        public Nullable<int> id_sesudah { get; set; }
    
        public virtual perusahaan perusahaan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<simo_detail> simo_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<simo> simo1 { get; set; }
        public virtual simo simo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<simo> simo11 { get; set; }
        public virtual simo simo3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<simo_remind_date> simo_remind_date { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<simo_remind_weekly> simo_remind_weekly { get; set; }
        public virtual User User { get; set; }
    }
}
