//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class simo_detail_pic
    {
        public int id_detail_pic { get; set; }
        public Nullable<int> id_detail { get; set; }
        public Nullable<int> divisi { get; set; }
        public Nullable<int> pic { get; set; }
        public string npk { get; set; }
    
        public virtual divisi divisi1 { get; set; }
        public virtual simo_detail simo_detail { get; set; }
        public virtual User User { get; set; }
    }
}
