//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public int idUserRoles { get; set; }
        public Nullable<int> id_hirarki { get; set; }
        public Nullable<int> id_divisi { get; set; }
        public Nullable<int> idRoleAtasan { get; set; }
    
        public virtual divisi divisi { get; set; }
        public virtual hirarki hirarki { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
